"""create menu_items table

Revision ID: 6319aa944bc3
Revises: b6446b3796c3
Create Date: 2026-09-17 10:35:52.728563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6319aa944bc3"
down_revision: Union[str, Sequence[str], None] = "b6446b3796c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
    "category",
    sa.Enum(
        "BURGER",
        "PIZZA",
        "PASTA",
        "SANDWICH",
        "WRAP",
        "RICE",
        "SALAD",
        "STARTER",
        "DESSERT",
        "BEVERAGE",
        "COMBO",
        "OTHER",
        name="menucategory",
    ),
    nullable=False,
),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_menu_items_name"), "menu_items", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_menu_items_name"), table_name="menu_items")
    op.drop_table("menu_items")
    # ### end Alembic commands ###
